---
coeu_graphhopper_name: graphhopperinstance
cops_graphhopper_git_url: "https://github.com/graphhopper/graphhopper.git"
cops_graphhopper_git_ver: "master"
cops_graphhopper_project_module_name: "{{cops_graphhopper_name}}"
cops_graphhopper_settings_module: "{{cops_graphhopper_project_module_name}}.settings.instances.{{cops_graphhopper_deploy_env}}"
cops_graphhopper_deploy_env: "dev"
cops_graphhopper_docker_image: "{{cops_graphhopper_name}}"
cops_graphhopper_default_docker_tag: "latest"
cops_graphhopper_docker_tag: "{{cops_graphhopper_default_docker_tag}}"
cops_graphhopper_tld_domain: example.com
cops_graphhopper_default_gitref: "master"
cops_graphhopper_gitref: "{{cops_graphhopper_default_gitref}}"
cops_graphhopper_dir: "/srv/docker/{{cops_graphhopper_name}}"
cops_graphhopper_lb_dir: "/srv/docker/graphhopper-lb"
cops_graphhopper_checkout_dir: "{{cops_graphhopper_dir}}/graphhopperclone"
cops_graphhopper_compose_lb_dir: "{{cops_graphhopper_lb_dir}}"
cops_graphhopper_compose_dir: "{{cops_graphhopper_checkout_dir}}"
cops_graphhopper_hostname: "{{cops_graphhopper_deploy_env}}-{{cops_graphhopper_name}}.{{cops_graphhopper_tld_domain}}"
cops_graphhopper_alternate_hostnames: [".{{cops_graphhopper_tld_domain}}"]
cops_graphhopper_gateway: "{{ ansible_default_ipv4.address}}"
cops_graphhopper_composename: "{{cops_graphhopper_name}}"
cops_graphhopper_lb_composename: "{{cops_graphhopper_name}}-lb"
cops_graphhopper_build_args: "--no-cache --pull graphhopper-yang"
cops_graphhopper_lb_build_args: "--no-cache --pull"
# backup could be remove in a-while when we have redeployed it everywhere
cops_graphhopper_restarted_services_default: "graphhopper-ying graphhopper-yang traefik"
cops_graphhopper_lb_restarted_services_default: "traefik"
cops_graphhopper_restarted_services: "{{cops_graphhopper_restarted_services_default}}"
cops_graphhopper_lb_restarted_services: "{{cops_graphhopper_lb_restarted_services_default}}"
cops_graphhopper_lb_purge_volumes: []
cops_graphhopper_purge_volumes: []
cops_graphhopper_sshargs: >-
  {% set k = hostvars[inventory_hostname].get(
                'ansible_ssh_private_key_file', '') %}
  {% if k%}-o IdentityFile={{k}} -o IdentitiesOnly=yes{%endif%}
  {% if (
      hostvars[inventory_hostname].ansible_connection|default('ssh')
     ) not in [ 'smart', 'local'] %}
  {{ hostvars[inventory_hostname].ssh_args | default('') }}
  {{ hostvars[inventory_hostname].ansible_ssh_args | default('') }}
  {{ hostvars[inventory_hostname].ansible_ssh_common_args | default('') }}
  {{ hostvars[inventory_hostname].ansible_ssh_extra_args | default('') }}
  {% endif %}
cops_graphhopper_lb_build: false
cops_graphhopper_build: true
cops_graphhopper_pull: true
cops_graphhopper_registries: []
#- {registry: registry.foo.net, username: foo, password: bar}
cops_graphhopper_compose_lb_files: [docker-compose.yml, docker-compose-prod.yml]
cops_graphhopper_compose_files: [docker-compose.yml, docker-compose-prod.yml]
cops_graphhopper_dc:
  docker-compose {% for i in cops_graphhopper_compose_files %} -f {{i}}{% endfor %}
  -p "{{cops_graphhopper_composename}}"
cops_graphhopper_lb_dc:
  docker-compose {% for i in cops_graphhopper_compose_lb_files %} -f {{i}}{% endfor %}
  -p "{{cops_graphhopper_lb_composename}}"
cops_graphhopper_hosts_whitelist: "{{(
    [cops_graphhopper_hostname, '0.0.0.0', '.{0}'.format(cops_graphhopper_hostname)]+
    cops_graphhopper_alternate_hostnames
  )|join('-|_')}}"
cops_graphhopper_lb_docker_env_freeform: |-
  {{ cops_graphhopper_lb_docker_env_defaults}}
  {{ cops_graphhopper_lb_docker_env_extra}}
cops_graphhopper_lb_docker_env_defaults: ""
cops_graphhopper_lb_docker_env_extra: ""
cops_graphhopper_docker_env_freeform: |-
  {{ cops_graphhopper_docker_env_defaults}}
  {{ cops_graphhopper_docker_env_extra}}
cops_graphhopper_docker_env_defaults: |-
  #
# very small, perfect for testing purpose
cops_graphhopper_pull_args: "traefik"
cops_graphhopper_force_dwn: "1"
cops_graphhopper_pbfs: "/data/europe_france_mayotte.pbf"
cops_graphhopper_mem: "1g"
cops_graphhopper_metaspacesize: "100M"
cops_graphoppper_cfg_graph_flag_encoders: "car,bike,foot"
cops_graphoppper_cfg_prepare_ch_weightings: fastest
cops_graphoppper_cfg_prepare_lm_weightings: fastest
cops_graphoppper_cfg_graph_dataaccess: RAM_STORE
cops_graphhopper_xmx: "{{cops_graphhopper_mem}}"
cops_graphhopper_xms: "{{cops_graphhopper_mem}}"
cops_graphhopper_javaopts: >-
  -server -Xconcurrentio
  -Xmx{{cops_graphhopper_xmx}} -Xms{{cops_graphhopper_xms}}
  -XX:+UseG1GC
  -XX:MetaspaceSize={{cops_graphhopper_metaspacesize}}
  -XX:MetaspaceSize=512M -XX:MaxMetaspaceSize=1024M
  -XX:+UseStringDeduplication
  -XX:+UnlockExperimentalVMOptions
  -XX:G1NewSizePercent=20
  -XX:+ParallelRefProcEnabled
  -XX:+ExplicitGCInvokesConcurrent
  -XX:MaxMetaspaceExpansion=64M
# free form for params inside dockerenv
cops_graphhopper_lb_dotenv_extra: ""
cops_graphhopper_lb_dotenv: |-
  COMPOSE_PROJECT_NAME={{cops_graphhopper_lb_composename}}
cops_graphhopper_dotenv: |-
  APP_TYPE=graphhopper
  COMPOSE_PROJECT_NAME={{cops_graphhopper_composename}}
  CI_COMMIT_SHA={{cops_graphhopper_gitref}}
  GRAPHHOPPER_NAME={{ cops_graphhopper_name }}
  GRAPHHOPPER_IMAGE={{ cops_graphhopper_docker_image }}
  GRAPHHOPPER_IMAGE_VERSION={{cops_graphhopper_docker_tag}}
  JAVA_OPTS={{cops_graphhopper_javaopts}}
  FORCE_DWN={{cops_graphhopper_force_dwn}}
  GRAPHHOPPER_PBFS={{cops_graphhopper_pbfs}}
  GRAPHHOPPER_CACHE_BACKEND_EXPIRY={{cops_graphhopper_cache_backend_expiry}}
cops_graphhopper_cache_backend_expiry: 43200
cops_graphhopper_dotenv_extra: ""
# free form for params inside dockerenv
cops_graphhopper_docker_env_extra: ""
# free form for params inside local.py
cops_graphhopper_localpy_extra: ""
# Normally playbook is in ./.ansible/playbooks
cops_graphhopper_code_dir: "{{playbook_dir}}/../.."
cops_graphhopper_out_ip: "{{cops_graphhopper_gateway}}"
cops_graphhopper_lb_http_port: 80
cops_graphhopper_lb_https_port: null
cops_graphhopper_http_port: 11112
cops_graphhopper_https_port: null
cops_graphhopper_ying_port: "{{(cops_graphhopper_http_port|int)+2}}"
cops_graphhopper_yang_port: "{{(cops_graphhopper_ying_port|int)+3}}"
cops_graphhopper_proxied: []
cops_graphhopper_group: prod
cops_graphhopper_traefik_extra: ""
cops_graphhopper_proxied_groups: |-
  {%- set res = [] %}
  {%- for i in cops_graphhopper_proxied %}
  {%- set _ = res.append("{}-{}".format(cops_graphhopper_group, i)) %}
  {%- endfor %}
  {{- res | tojson }}
cops_graphhopper_code_rsync_opts: [
    "-azv",
    # include deploy projects base code
    "--include", "local/*-deploy",
    "--exclude", ".ansible",
    "--exclude", "local/*",
    "--exclude", ".env",
    "--exclude", "docker.env"]
