---
graphhopper_servers: graphhopper_servers
cops_graphhopper_name: "graphhopper"
cops_graphhopper_tld_domain: "example.net"
cops_graphhopper_hostname:  "{{cops_graphhopper_name}}.{{cops_graphhopper_tld_domain}}"
cops_graphhopper_alternate_hostnames: ["www.{{cops_graphhopper_hostname}}"]
cops_graphhopper_gitref: "{{lookup('env', 'CI_COMMIT_TAG_NAME') or lookup('env', 'CI_COMMIT_REF_NAME') or 'latest'}}"
cops_graphhopper_docker_tag: "{{cops_graphhopper_gitref.replace('master', 'latest')}}"
cops_graphhopper_docker_env_extra: |-
  # db
