version: '3.7'
services:
  traefik:
    restart: unless-stopped
    ports:
    - "0.0.0.0:{{cops_graphhopper_lb_http_port}}:80"
    {% if cops_graphhopper_lb_https_port %}- "0.0.0.0:{{cops_graphhopper_lb_https_port}}:443"{%endif%}
