---
ssh_envs:
  hosts:
    myhost-fr.example.net:
    myhost-eu.example.net:
    myhost-world.example.net:
    myhost-lb.example.net:

myhost-loc:
  vars: {ansible_host: localhost, ansible_connection: local}
  hosts:
    prod_loc-docker-graphhopper-fr:
    prod_loc-docker-graphhopper-eu:
    prod_loc-docker-graphhopper-world:
    prod_loc-docker-graphhopper-lb:

myhost.example.net:
  vars: {
    ansible_host: myhost.example.net, ansible_port: "40001"}
  hosts:
    myhost-fr.example.net:
    myhost-eu.example.net:
    myhost-world.example.net:
    myhost-lb.example.net:

prod-fr:    {hosts: {myhost-fr.example.net: null}}
prod-eu:    {hosts: {myhost-eu.example.net: null}}
prod-world: {hosts: {myhost-world.example.net: null}}
prod-lb:    {hosts: {myhost-lb.example.net: null}}

prod_loc-fr:    {hosts: {prod_loc-docker-graphhopper-fr: null}}
prod_loc-eu:    {hosts: {prod_loc-docker-graphhopper-eu: null}}
prod_loc-world: {hosts: {prod_loc-docker-graphhopper-world: null}}
prod_loc-lb:    {hosts: {prod_loc-docker-graphhopper-lb: null}}

prod-graphhopper:
  children:
    prod-fr:
    prod-eu:
    prod-world:
prod_loc-graphhopper:
  children:
    prod_loc-fr:
    prod_loc-eu:
    prod_loc-world:

prod:
  children:
    prod-graphhopper:
    prod-lb:
prod_loc:
  children:
    prod_loc-graphhopper:
    prod_loc-lb:

graphhopper_servers:
  children:
    prod:
    prod_loc:
lb_servers:
  children:
    prod-lb:
    prod_loc-lb:
